In [ ]:
From: https://github.com/ksatola
Version: 1.0.0

# Python Visualization Dashboards with Plotly's Dash - Part 1

## Table of Contents

- [Introduction](#intro)
- [Environment Setup](#set)
- [Data Visualization libraries for Python](#libs)
- [Numpy Crash Course](#np)
- [Pandas Crash Course](#pd)
- [Plotly Basics](#plotly)
    - [Scatter Plots](#plotly-scat)
    - [Line Charts](#plotly-line)
    - [Bar Charts](#plotly-bar)
    - [Bubble Plots](#plotly-bub)
    - [Box Plots](#plotly-box)
    - [Histograms](#plotly-his)
    - [Distplots](#plotly-dis)
    - [Heatmaps](#plotly-heat)
- [Resources](#res)

---
<a id='intro'></a>

## Introduction

This notebook will teach your everything you need to know to use Python to create interactive dashboard's with Plotly's new Dash library! You will be able to create fully customization, interactive dashboards with the open source libraries of Plotly and Dash.

Contents:
- Learn about Plotly to create plots like Bar Charts, Line Charts, Scatter Plots, Heat Maps, and more!
- Create Layouts with Plotly's Dash library.
- Use Dash to create interactive components with Plotly.
- Learn how to connect multiple inputs and outputs with a dashboard.
- Update live interactive graphs with clicks, hover overs, and more.
- Connect the interactive dashboard to live updating data for streaming information.
- Learn how to secure your interactive dashboards with App Authorization.
- Deploy your interactive dashboards to the internet with services like Heroku.

---
<a id='set'></a>

## Environment Setup
- Install Python interpreter
- [Install Atom IDE](https://atom.io/)
- Install Atom's packages:
    - autocomplete-python package + kite ML package
    - platformio-ide-terminal / atom-terminal
- Configure Python virtual environment

In [ ]:
# Configuring Python virtual environment
$ cd DashCourse/
$ pip install virtualenv
$ virtualenv dashenv
bash -> $ source dashenv/bin/activate
fish -> $ source dashenv/bin/activate.fish
# $ deactivate
$ pip install -r requirements.txt

---
<a id='libs'></a>

## Data Visualization libraries for Python

- **Matplotlib** for static image files.
- **Seaborn**, based on Matplotlib, designed to show static statistics plots, have cleaner syntax but only plots described in its documnetation are available.
- **Pandas**, main purpose is data analysis but uses simple .plot() calls (based on Matplotlib), limited scope of plot types, static plots.
- **Plotly** 
    - An open source general data visualization library focused on interactive visualizations. It has libraries for JavaScript, React, R and Python. 
    - The plots themselves cannot be connected to dynamic data sources (they are HTML files containing data visualization as of publishing). For that, they need **Dash**.
- **Dash** 
    - Allows you to create a full dashboard with multiple components, interactivity, and mutliple plots.
    - Produce a web application dashboard.

---
<a id='np'></a>

## Numpy Crash Course

**NumPy** is a scientific computing and mathematical library.

In [1]:
import numpy as np

In [2]:
mylist = [1,2,3,4]
np.array(mylist)

array([1, 2, 3, 4])

In [3]:
type(mylist)

list

In [4]:
arr = np.array(mylist)
type(arr)

numpy.ndarray

In [5]:
# Create np arrays
a = np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a = np.arange(0,10,2)
a

array([0, 2, 4, 6, 8])

In [7]:
# 2-dimensional array
# rows,cols
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
type(1)

int

In [11]:
type(1.)

float

In [12]:
# Generate a random number within a range
np.random.randint(0,100)

95

In [13]:
# Create a random matrix (5,5) of integers 
# (uniform distribution, every number has the same likelihood of being picked)
np.random.randint(0,100,(5,5))

array([[ 3, 18, 85, 74, 69],
       [26, 84, 92, 58, 23],
       [47, 91, 57, 96, 21],
       [ 3, 97, 20, 25, 80],
       [56, 56, 85, 14, 61]])

In [14]:
# Create linearily spaced array bewteen 0,10 of 7 elements
np.linspace(0,10,7)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

In [15]:
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [16]:
np.linspace(0,10,12)

array([ 0.        ,  0.90909091,  1.81818182,  2.72727273,  3.63636364,
        4.54545455,  5.45454545,  6.36363636,  7.27272727,  8.18181818,
        9.09090909, 10.        ])

In [17]:
# Generate the same random numbers over and over again
np.random.seed(101)

In [18]:
np.random.randint(0,100,10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [19]:
arr = np.random.randint(0,100,100)
arr

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40, 49, 83,  8, 29, 59, 34, 44,
       72, 19, 10, 76, 95, 87,  0, 73,  8, 62, 36, 83, 99, 28, 63,  7, 10,
       52, 56, 38, 73, 52, 18, 71, 15, 44,  0, 12, 17, 75, 79, 97, 93, 24,
       36, 63, 19, 35, 30, 10, 60, 20, 27,  8, 86, 26, 87, 46, 47, 54, 86,
        9, 45,  2, 18, 58, 92, 11, 10, 94, 35, 28,  3, 83, 84, 47, 14, 69,
       60, 69, 51,  6, 88, 71, 68, 23, 35, 79, 98, 67, 82, 57, 77])

In [20]:
arr.max()

99

In [21]:
arr.min()

0

In [22]:
arr.mean()

47.96

In [23]:
# Get back an zero-based index location for the max value(s)
arr.argmax()

29

In [24]:
arr.argmin()

23

In [25]:
# Reshape your arr into another dimenstions
arr = np.random.randint(0,100,10)
arr

array([46,  3, 46, 29, 86, 21, 21, 81, 23, 94])

In [26]:
# rows, cols
arr.reshape(2,5)

array([[46,  3, 46, 29, 86],
       [21, 21, 81, 23, 94]])

In [27]:
# Build a matrix
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [28]:
# Get a specific value
# row, col
mat[5,2]

52

In [29]:
# Get entire column
# all rows, second column
col = mat[:,2]
col

array([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])

In [30]:
col.reshape(10,1)

array([[ 2],
       [12],
       [22],
       [32],
       [42],
       [52],
       [62],
       [72],
       [82],
       [92]])

In [31]:
# Get entire row
# row 2, all columns
row = mat[2,:]
row

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [32]:
# No need to reshape for rows
row.reshape(1,10)

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [33]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [34]:
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [35]:
# Get only values where values are > 50
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

---
<a id='pd'></a>

## Pandas Crash Course

**Pandas** is a library built on top of **NumPy** which allows Python to read in data sets from various formats, such as CSV files. It provides a conveniest way of wrangling data in tabular form and calculate statistics.

In [36]:
import pandas as pd

In [37]:
df = pd.read_csv("data/udemy/dash/salaries.csv")
print(df)

     Name  Salary  Age
0    John   50000   34
1   Sally  120000   45
2  Alyssa   80000   27


In [38]:
# A series
df["Salary"]

0     50000
1    120000
2     80000
Name: Salary, dtype: int64

In [39]:
# A dataframe
df[["Salary"]]

Salary
0   50000
1  120000
2   80000

In [40]:
df[["Name", "Salary"]]

Name  Salary
0    John   50000
1   Sally  120000
2  Alyssa   80000

In [41]:
df["Salary"].min()

50000

In [42]:
df["Salary"].mean()

83333.33333333333

In [43]:
df

Name  Salary  Age
0    John   50000   34
1   Sally  120000   45
2  Alyssa   80000   27

In [44]:
# Conditional filtering
ser_of_bool = df["Age"] > 30
ser_of_bool

0     True
1     True
2    False
Name: Age, dtype: bool

In [45]:
df[ser_of_bool]

Name  Salary  Age
0   John   50000   34
1  Sally  120000   45

In [46]:
df[df["Age"] > 30]

Name  Salary  Age
0   John   50000   34
1  Sally  120000   45

In [47]:
# Show unique values in a Series
df[df["Age"] > 30]["Age"].unique()

array([34, 45])

In [48]:
# Show a number of unique values in a Series
df[df["Age"] > 30]["Age"].nunique()

2

In [49]:
df.columns

Index(['Name', 'Salary', 'Age'], dtype='object')

In [50]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
Name      3 non-null object
Salary    3 non-null int64
Age       3 non-null int64
dtypes: int64(2), object(1)
memory usage: 200.0+ bytes


In [52]:
df.describe()

Salary        Age
count       3.000000   3.000000
mean    83333.333333  35.333333
std     35118.845843   9.073772
min     50000.000000  27.000000
25%     65000.000000  30.500000
50%     80000.000000  34.000000
75%    100000.000000  39.500000
max    120000.000000  45.000000

In [53]:
# Create a dataframe from a numpy array
mat = np.arange(0,50).reshape(5,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [54]:
df = pd.DataFrame(data=mat)
df

0   1   2   3   4   5   6   7   8   9
0   0   1   2   3   4   5   6   7   8   9
1  10  11  12  13  14  15  16  17  18  19
2  20  21  22  23  24  25  26  27  28  29
3  30  31  32  33  34  35  36  37  38  39
4  40  41  42  43  44  45  46  47  48  49

In [55]:
mat = np.arange(0,10).reshape(5,2)
mat

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [56]:
df = pd.DataFrame(data=mat, columns=['A', 'B'], index=['a', 'b', 'c', 'd', 'e'])
df

A  B
a  0  1
b  2  3
c  4  5
d  6  7
e  8  9

In [57]:
l = 'A B C D'.split()
l

['A', 'B', 'C', 'D']

---
<a id='plotly'></a>

## Plotly Basics

- **[Plotly examples](https://plot.ly/python/)**
- **[Python Figure Reference](https://plot.ly/python/reference/)**

---
<a id='plotly-scat'></a>

### Scatter Plots

In [ ]:
# Imports
import numpy as np
import plotly.offline as pyo
import plotly.graph_objs as go

In [ ]:
# Random data
np.random.seed(42)
random_x = np.random.randint(1,101,100)
random_y = np.random.randint(1,101,100)

In [ ]:
# Scatter plot
data = [go.Scatter(x=random_x, y=random_y, mode='markers')]
pyo.plot(data, filename='dash/var/scatter.html')

In [ ]:
data

In [ ]:
# Enhanced scatter plot
data = [go.Scatter(x=random_x, y=random_y, mode='markers')]
layout = go.Layout(title='Scatter Plot',
                  xaxis={'title':'X-Axis'},
                  yaxis=dict(title='Y-Axis'),
                  hovermode='closest')
fig = go.Figure(data=data, layout=layout)
pyo.plot(fig, filename='dash/var/scatter2.html')

In [ ]:
fig

In [ ]:
# Bigger points
data = [go.Scatter(x=random_x, 
                   y=random_y, 
                   mode='markers', 
                   marker=dict(
                       size=12,
                       color='rgb(51,204,153)',
                       symbol='pentagon',
                       line={'width':2}
                   ))]
layout = go.Layout(title='Scatter Plot',
                  xaxis={'title':'X-Axis'},
                  yaxis=dict(title='Y-Axis'),
                  hovermode='closest')
fig = go.Figure(data=data, layout=layout)
pyo.plot(fig, filename='dash/var/scatter3.html')

In [ ]:
fig

---
<a id='plotly-line'></a>

### Line Charts

In [ ]:
import numpy as np
import plotly.offline as pyo
import plotly.graph_objs as go

In [ ]:
np.random.seed(56)
# from 0-1 give me 100 evenly spaced values
x_values = np.linspace(0,1,100)
# from normal distribution give me 100 random values
y_values = np.random.randn(100)

In [ ]:
trace = go.Scatter(x=x_values, 
                   y=y_values+5, 
                   mode='markers',
                   name='markers')
data = [trace]
layout = go.Layout(title="Line Charts")
fig = go.Figure(data=data, layout=layout)
pyo.plot(fig, filename='dash/var/line.html')

In [ ]:
data

In [ ]:
fig

In [ ]:
trace0 = go.Scatter(x=x_values, 
                   y=y_values+5, 
                   mode='markers',
                   name='markers')
trace1 = go.Scatter(x=x_values, 
                   y=y_values, 
                   mode='lines',
                   name='line')
data = [trace0, trace1]
layout = go.Layout(title="Line Charts")
fig = go.Figure(data=data, layout=layout)
pyo.plot(fig, filename='dash/var/line2.html')

In [ ]:
fig

In [ ]:
trace0 = go.Scatter(x=x_values, 
                   y=y_values+5, 
                   mode='markers',
                   name='markers')
trace1 = go.Scatter(x=x_values, 
                   y=y_values, 
                   mode='lines',
                   name='line')
trace2 = go.Scatter(x=x_values, 
                   y=y_values-5, 
                   mode='lines+markers',
                   name='line with markers')
data = [trace0, trace1, trace2]
layout = go.Layout(title="Line Charts")
fig = go.Figure(data=data, layout=layout)
pyo.plot(fig, filename='dash/var/line3.html')

In [ ]:
fig

In [ ]:
# Use "real data"
df = pd.read_csv('data/udemy/dash/nst-est2017-alldata.csv')
df.head()

In [ ]:
# Filter df to get data for plots (population estimates)
df2 = df[df['DIVISION'] == '1']
df2.set_index('NAME', inplace=True)
list_of_pop_cols = [col for col in df2.columns if col.startswith('POP')]
df2 = df2[list_of_pop_cols]
df2.head()

In [ ]:
data = [go.Scatter(x=df2.columns, 
                   y=df2.loc[name], 
                   mode='lines', 
                   name=name) for name in df2.index]
pyo.plot(data, filename='dash/var/line4.html')

In [ ]:
import numpy as np
import pandas as pd
import plotly.offline as pyo
import plotly.graph_objs as go

#### Ex - Approach 1 (complicated)

In [ ]:
#######
# Objective: Using the file 2010YumaAZ.csv, develop a Line Chart
# that plots seven days worth of temperature data on one graph.
# You can use a for loop to assign each day to its own trace.
######

In [ ]:
# Create a pandas DataFrame from 2010YumaAZ.csv
df = pd.read_csv('data/udemy/dash/2010YumaAZ.csv')
days = ['TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY','SUNDAY','MONDAY']
df.head()

In [ ]:
def format_time(t):
    if len(t) == 4:
        t = '0' + t
    return t

In [ ]:
df['LST_TIME'] = df['LST_TIME'].apply(format_time)
df.head()

In [ ]:
df2 = df.pivot(index='DAY', columns='LST_TIME', values='T_HR_AVG')
df2.head()

In [ ]:
data = [go.Scatter(x=df2.columns, 
                   y=df2.loc[day], 
                   mode='lines', 
                   name=day) for day in df2.index]
pyo.plot(data, filename='dash/var/line5.html')

#### Ex - Approach 2 (simple)

In [ ]:
# Create a pandas DataFrame from 2010YumaAZ.csv
df = pd.read_csv('data/udemy/dash/2010YumaAZ.csv')
days = ['TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY','SUNDAY','MONDAY']
df.head()

In [ ]:
data = []

for day in days:
    # What should go inside this Scatter call?
    trace = go.Scatter(x=df['LST_TIME'],
                      y=df[df['DAY']==day]['T_HR_AVG'],
                      mode='lines',
                      name=day)
    data.append(trace)

In [ ]:
# Or using a list comprehension and without static days list
#days = df['DAY'].unique()

data = [{
    'x': df['LST_TIME'],
    'y': df[df['DAY']==day]['T_HR_AVG'],
    'name': day
} for day in df['DAY'].unique()]

In [ ]:
layout = go.Layout(title="Daily temp avgs")

In [ ]:
fig = go.Figure(data=data, layout=layout)
pyo.plot(fig, filename='dash/var/line6.html')

In [ ]:
fig

---
<a id='plotly-bar'></a>

### Bar Charts

In [ ]:
import plotly.offline as pyo
import plotly.graph_objs as go
import pandas as pd

In [ ]:
df = pd.read_csv('data/udemy/dash/2018WinterOlympics.csv')
df.head()

In [ ]:
data = [go.Bar(x=df['NOC'],
              y=df['Total'])]
layout = go.Layout(title='Medals')
fig = go.Figure(data=data, layout=layout)
pyo.plot(fig, filename='dash/var/bar.html')

In [ ]:
fig

In [ ]:
# Nested Bar Chart
trace1 = go.Bar(x=df['NOC'],
              y=df['Gold'],
               name='Gold',
               marker={'color':'#FFD700'})
trace2 = go.Bar(x=df['NOC'],
              y=df['Silver'],
               name='Silver',
               marker={'color':'#9EA0A1'})
trace3 = go.Bar(x=df['NOC'],
              y=df['Bronze'],
               name='Bronze',
               marker={'color':'#CD7F32'})
data = [trace1, trace2, trace3]
layout = go.Layout(title='Medals')
fig = go.Figure(data=data, layout=layout)
pyo.plot(fig, filename='dash/var/bar2.html')

In [ ]:
fig

In [ ]:
# Stack Bar Chart
layout = go.Layout(title='Medals', barmode='stack')
fig = go.Figure(data=data, layout=layout)
pyo.plot(fig, filename='dash/var/bar3.html')

In [ ]:
fig

#### Ex

In [ ]:
#######
# Objective: Create a stacked bar chart from
# the file ../data/mocksurvey.csv. Note that questions appear in
# the index (and should be used for the x-axis), while responses
# appear as column labels.  Extra Credit: make a horizontal bar chart!
######

In [ ]:
import plotly.offline as pyo
import plotly.graph_objs as go
import pandas as pd

In [ ]:
df = pd.read_csv('data/udemy/dash/mocksurvey.csv', index_col=0)
df.head()

In [ ]:
#trace = go.Bar(x=df.index, y=df['Strongly Agree'], name='Strongly Agree')
traces = [go.Bar(x=df.index, y=df[column], name=column) for column in df.columns]
data = traces
layout = go.Layout(title='Survey', barmode='stack')
fig = go.Figure(data=data, layout=layout)
pyo.plot(fig, filename='dash/var/bar4.html')

In [ ]:
fig

In [ ]:
# Horizontal orientation (reverse x and y and add orientation)
traces = [go.Bar(y=df.index, x=df[column], name=column, orientation='h') for column in df.columns]
data = traces
layout = go.Layout(title='Survey', barmode='stack')
fig = go.Figure(data=data, layout=layout)
pyo.plot(fig, filename='dash/var/bar5.html')

In [ ]:
fig

---
<a id='plotly-bub'></a>

### Bubble Plots

In [ ]:
import plotly.offline as pyo
import plotly.graph_objs as go
import pandas as pd

In [ ]:
df = pd.read_csv('data/udemy/dash/mpg.csv')
df.head()

In [ ]:
data = [go.Scatter(x=df['horsepower'],
                  y=df['mpg'],
                  text=df['name'],
                  mode='markers',
                  marker=dict(size=2*df['cylinders']))] # multiply for better visibility
layout = go.Layout(title='Bubble Chart')
fig = go.Figure(data=data, layout=layout)
pyo.plot(fig, filename='dash/var/bubble.html')

In [ ]:
fig

In [ ]:
data = [go.Scatter(x=df['horsepower'],
                  y=df['mpg'],
                  text=df['name'],
                  mode='markers',
                  marker=dict(size=df['weight']/200))] # divide for better visibility
layout = go.Layout(title='Bubble Chart')
fig = go.Figure(data=data, layout=layout)
pyo.plot(fig, filename='dash/var/bubble2.html')

In [ ]:
fig

In [ ]:
data = [go.Scatter(x=df['horsepower'],
                  y=df['mpg'],
                  text=df['name'],
                  mode='markers',
                  marker=dict(size=df['weight']/200, # divide for better visibility
                              color=df['cylinders'],
                              showscale=True
                             ))] 
#layout = go.Layout(title='Bubble Chart', hovermode='x')
#layout = go.Layout(title='Bubble Chart', hovermode='y')
layout = go.Layout(title='Bubble Chart', hovermode='closest')
fig = go.Figure(data=data, layout=layout)
pyo.plot(fig, filename='dash/var/bubble3.html')

In [ ]:
fig

#### Ex

In [ ]:
#######
# Objective: Create a bubble chart that compares three other features
# from the mpg.csv dataset. Fields include: 'mpg', 'cylinders', 'displacement'
# 'horsepower', 'weight', 'acceleration', 'model_year', 'origin', 'name'
######

In [ ]:
import plotly.offline as pyo
import plotly.graph_objs as go
import pandas as pd

In [ ]:
df = pd.read_csv('data/udemy/dash/mpg.csv')
df.head()

In [ ]:
data = [go.Scatter(x=df['horsepower'],
                  y=df['model_year'],
                  text=df['name'],
                  mode='markers',
                  marker=dict(size=df['cylinders']*2, # divide for better visibility
                              color=df['mpg'],
                              showscale=True
                             ))] 
#layout = go.Layout(title='Bubble Chart', hovermode='x')
#layout = go.Layout(title='Bubble Chart', hovermode='y')
layout = go.Layout(title='Horspower vs. Model Year, Size: Cylinders, Color: MPG', 
                   xaxis=dict(title='Horsepower'),
                   yaxis=dict(title='Model Year'),
                   hovermode='closest')
fig = go.Figure(data=data, layout=layout)
pyo.plot(fig, filename='dash/var/bubble4.html')

In [ ]:
fig

---
<a id='plotly-box'></a>

### Box Plots

- **Upper Outliers** are values larger than Q3 by at least 1.5 time the **IQR**.
- **Lower Outlier** are values smaller than Q1 by at least 1.5 times the **IQR**.
- **Higher wisker** is no bigger than 1.5 times the **IQR**. If there are no outliers in the max. direction, it also shows the max. value.
- **Lower wisker** is no smaller than 1.5 times the **IQR**. If there are no outliers in the min. direction, it also shows the min. value.

In [ ]:
import plotly.offline as pyo
import plotly.graph_objs as go

In [ ]:
# set up an array of 20 data points, with 20 as the median value
y = [1,14,14,15,16,18,18,19,19,20,20,23,24,26,27,27,28,29,33,54]

In [ ]:
data = [
    go.Box(y=y)]
fig = go.Figure(data=data)
pyo.plot(data, filename='dash/var/box.html')

In [ ]:
fig

In [ ]:
data = [
    go.Box(
        y=y,
        boxpoints='all', # display the original data points
        jitter=0.3,      # spread them out so they all appear
        pointpos=-1.8    # offset them to the left of the box
    )
]
fig = go.Figure(data=data)
pyo.plot(data, filename='dash/var/box2.html')

In [ ]:
fig

In [ ]:
data = [
    go.Box(
        y=y,
        boxpoints='all', # display the original data points
        jitter=0.1,      # spread them out so they all appear
        pointpos=0    # offset them to the left of the box
    )
]
fig = go.Figure(data=data)
pyo.plot(data, filename='dash/var/box3.html')

In [ ]:
fig

In [ ]:
data = [
    go.Box(
        y=y,
        boxpoints='outliers', # display only outlying data points
    )
]
fig = go.Figure(data=data)
pyo.plot(data, filename='dash/var/box4.html')

In [ ]:
fig

In [ ]:
# Words frequencies of Snodgrass and Twain 3 letter words writing
snodgrass = [.209,.205,.196,.210,.202,.207,.224,.223,.220,.201]
twain = [.225,.262,.217,.240,.230,.229,.235,.217]

In [ ]:
data = [
    go.Box(
        y=snodgrass,
        name='Snodgrass'
    ),
    go.Box(
        y=twain,
        name='Twain'
    )
]
layout = go.Layout(
    title = 'Comparison of three-letter-word frequencies<br>\
    between Quintus Curtius Snodgrass and Mark Twain'
)
fig = go.Figure(data=data, layout=layout)
pyo.plot(fig, filename='dash/var/box5.html')

In [ ]:
fig

#### Ex

In [ ]:
#######
# Objective: Make a DataFrame using the Abalone dataset (../data/abalone.csv).
# Take two independent random samples of different sizes from the 'rings' field.
# HINT: np.random.choice(df['rings'],10,replace=False) takes 10 random values
# Use box plots to show that the samples do derive from the same population.
######

In [ ]:
import plotly.offline as pyo
import plotly.graph_objs as go
import pandas as pd

In [ ]:
df = pd.read_csv('data/udemy/dash/abalone.csv')
df.head()

In [ ]:
df.shape

In [ ]:
# Take 2 random samples of different sizes
sample1 = np.random.choice(df['rings'], 1000, replace=False)
sample2 = np.random.choice(df['rings'], 1200, replace=False)

In [ ]:
data = [
    go.Box(
        y=sample1,
        name='sample1'
    ),
    go.Box(
        y=sample2,
        name='sample2'
    )
]
layout = go.Layout(
    title = 'Comparison of 2 samples'
)
fig = go.Figure(data=data, layout=layout)
pyo.plot(fig, filename='dash/var/box6.html')

In [ ]:
fig

---
<a id='plotly-his'></a>

### Histograms
Displays an accurate representation of the overall distribution of a `continuous feature`. To create a **histogram**, we divide the entire range of values of the continuous feature into a series of intervals (`bins`). Then we count the number of occurences per bin (interval range). We can change the bin size to get either more or less details.

In [ ]:
import plotly.offline as pyo
import plotly.graph_objs as go
import pandas as pd

In [ ]:
df = pd.read_csv('data/udemy/dash/mpg.csv')
df.head()

In [ ]:
data = [go.Histogram(x=df['mpg'])]
layout = go.Layout(
    title = 'Histogram',
    hovermode='x'
)
fig = go.Figure(data=data, layout=layout)
pyo.plot(fig, filename='dash/var/hist.html')

In [ ]:
fig

In [ ]:
data = [go.Histogram(x=df['mpg'],
                    xbins=dict(start=0, # x min range
                               end=50, # x max range
                               size=10 # bin size
                              ))]
layout = go.Layout(
    title = 'Histogram',
    hovermode='x'
)
fig = go.Figure(data=data, layout=layout)
pyo.plot(fig, filename='dash/var/hist2.html')

In [ ]:
fig

In [ ]:
data = [go.Histogram(x=df['mpg'],
                    xbins=dict(start=0, # x min range
                               end=50, # x max range
                               size=2 # bin size
                              ))]
layout = go.Layout(
    title = 'Histogram',
    hovermode='x'
)
fig = go.Figure(data=data, layout=layout)
pyo.plot(fig, filename='dash/var/hist3.html')

In [ ]:
fig

#### Ex

In [ ]:
#######
# Objective: Create a histogram that plots the 'length' field
# from the Abalone dataset (../data/abalone.csv).
# Set the range from 0 to 1, with a bin size of 0.02
######

In [ ]:
import plotly.offline as pyo
import plotly.graph_objs as go
import pandas as pd

In [ ]:
df = pd.read_csv('data/udemy/dash/abalone.csv')
df.head()

In [ ]:
data = [go.Histogram(x=df['length'],
                    xbins=dict(start=0, # x min range
                               end=1, # x max range
                               size=0.02 # bin size
                              ))]
layout = go.Layout(
    title = 'Abalone Length Distribution',
    hovermode='x'
)
fig = go.Figure(data=data, layout=layout)
pyo.plot(fig, filename='dash/var/hist4.html')

In [ ]:
fig

---
<a id='plotly-dis'></a>

### Distribution Plots (Distplots)

**Distplots** typically layer three plots on top of one another. The first is a `histogram`, where each data point is placed inside a bin of similar values. The second is a `rug plot` - marks are placed along the x-axis for every data point, which lets you see the distribution of values inside each bin. Lastly, **distplots** often include a `kernel density estimate` or `KDE` line that tries to describe the shape of the distribution.

In [ ]:
import plotly.offline as pyo
import plotly.figure_factory as ff
import numpy as np

In [ ]:
# Create a sample of normaly distributed data
x = np.random.randn(1000)

In [ ]:
hist_data = [x]
group_labels = ['distplot']
fig = ff.create_distplot(hist_data, group_labels)
pyo.plot(fig, filename='dash/var/dist.html')

In [ ]:
fig

In [ ]:
# More groups
x1 = np.random.randn(200)-2
x2 = np.random.randn(200)
x3 = np.random.randn(200)+2
x4 = np.random.randn(200)+4

In [ ]:
hist_data = [x1, x2, x3, x4]
group_labels = ['X1', 'X2', 'X3', 'X4']
fig = ff.create_distplot(hist_data, group_labels, bin_size=[.2, .1, .3, .4])
pyo.plot(fig, filename='dash/var/dist2.html')

In [ ]:
fig

In [ ]:
snodgrass = [.209,.205,.196,.210,.202,.207,.224,.223,.220,.201]
twain = [.225,.262,.217,.240,.230,.229,.235,.217]

hist_data = [snodgrass,twain]
group_labels = ['Snodgrass','Twain']

fig = ff.create_distplot(hist_data, group_labels, bin_size=[.005,.005])
pyo.plot(fig, filename='dash/var/dist3.html')

In [ ]:
fig

#### Ex

In [ ]:
#######
# Objective: Using the iris dataset, develop a Distplot
# that compares the petal lengths of each class.
# File: '../data/iris.csv'
# Fields: 'sepal_length','sepal_width','petal_length','petal_width','class'
# Classes: 'Iris-setosa','Iris-versicolor','Iris-virginica'
######

In [ ]:
import plotly.offline as pyo
import plotly.figure_factory as ff
import pandas as pd

In [ ]:
df = pd.read_csv('data/udemy/dash/iris.csv')
df.head()

In [ ]:
#iris_class = df[df['class']=='Iris-setosa']['petal_length']
classes = [df[df['class']==iris_class]['petal_length'] for iris_class in df['class'].unique()]
#classes[2]

In [ ]:
hist_data = classes
group_labels = [label for label in df['class'].unique()]

fig = ff.create_distplot(hist_data, group_labels, bin_size=[.5, .5, .5])
pyo.plot(fig, filename='dash/var/dist4.html')

In [ ]:
fig

---
<a id='plotly-heat'></a>

### Heatmaps

**Heatmaps** allow the visualization of 3 features. `Categorical or continuous features` along the x and y axis to make up a grid, and then a `3rd continuous feature` displayed through color.

In [ ]:
import plotly.offline as pyo
import plotly.graph_objs as go
import pandas as pd

In [ ]:
df = pd.read_csv('data/udemy/dash/2010SantaBarbaraCA.csv')
df.head()

In [ ]:
data = [go.Heatmap(
    x=df['DAY'],
    y=df['LST_TIME'],
    z=df['T_HR_AVG'].values.tolist(), # have to be a list not a Series
    colorscale='Jet'
)]

layout = go.Layout(
    title='Hourly Temperatures, June 1-7, 2010 in<br>\
    Santa Barbara, CA USA'
)
fig = go.Figure(data=data, layout=layout)
pyo.plot(fig, filename='dash/var/heat.html')

In [ ]:
fig

In [ ]:
# Multiple heatmaps with subplots
#######
# Side-by-side heatmaps for Sitka, Alaska,
# Santa Barbara, California and Yuma, Arizona
# using a shared temperature scale.
######

In [ ]:
import plotly.offline as pyo
import plotly.graph_objs as go
from plotly import tools
import pandas as pd

In [ ]:
df1 = pd.read_csv('data/udemy/dash/2010SitkaAK.csv')
df2 = pd.read_csv('data/udemy/dash/2010SantaBarbaraCA.csv')
df3 = pd.read_csv('data/udemy/dash/2010YumaAZ.csv')

In [ ]:
trace1 = go.Heatmap(
    x=df1['DAY'],
    y=df1['LST_TIME'],
    z=df1['T_HR_AVG'],
    colorscale='Jet',
    zmin = 5, zmax = 40 # add max/min color values to make each plot consistent
)
trace2 = go.Heatmap(
    x=df2['DAY'],
    y=df2['LST_TIME'],
    z=df2['T_HR_AVG'],
    colorscale='Jet',
    zmin = 5, zmax = 40
)
trace3 = go.Heatmap(
    x=df3['DAY'],
    y=df3['LST_TIME'],
    z=df3['T_HR_AVG'],
    colorscale='Jet',
    zmin = 5, zmax = 40
)

In [ ]:
fig = tools.make_subplots(rows=1, cols=3,
    subplot_titles=('Sitka, AK','Santa Barbara, CA', 'Yuma, AZ'),
    shared_yaxes = True,  # this makes the hours appear only on the left
)
fig.append_trace(trace1, 1, 1)
fig.append_trace(trace2, 1, 2)
fig.append_trace(trace3, 1, 3)

In [ ]:
fig['layout'].update(      # access the layout directly!
    title='Hourly Temperatures, June 1-7, 2010'
)
pyo.plot(fig, filename='dash/var/heat2.html')

In [ ]:
fig

#### Ex

In [ ]:
#######
# Objective: Using the "flights" dataset available
# from the data folder as flights.csv
# create a heatmap with the following parameters:
# x-axis="year"
# y-axis="month"
# z-axis(color)="passengers"
######

In [ ]:
import plotly.offline as pyo
import plotly.graph_objs as go
import pandas as pd

In [ ]:
df = pd.read_csv('data/udemy/dash/flights.csv')
df.head()

In [ ]:
data = [go.Heatmap(
    x=df['year'],
    y=df['month'],
    z=df['passengers'].values.tolist() # have to be a list not a Series
)]

layout = go.Layout(
    title='Thousands of passengers flying over years and months'
)
fig = go.Figure(data=data, layout=layout)
pyo.plot(fig, filename='dash/var/heat3.html')

In [ ]:
fig

---
<a id='res'></a>

## Resources

- [Course notes](https://github.com/Pierian-Data/Plotly-Dashboards-with-Dash)
- [Guide book](https://docs.google.com/document/d/1DjWL2DxLiRaBrlD3ELyQlCBRu7UQuuWfgjv9LncNp_M/edit?usp=sharing)
- [Public datasets](https://docs.google.com/document/d/1vI84_EpRTh4xfcFkTunFzZT0RWMcRSqdkPueVNBcLx8/edit)