From: https://github.com/ksatola
Version: 0.0.1

# Python Visualization Dashboards with Plotly's Dash

## Table of Contents

- [Introduction](#intro)
- [Environment Setup](#set)
- [Data Visualization libraries for Python](#libs)
- [Numpy Crash Course](#np)
- [Pandas Crash Course](#pd)
- [Resources](#res)


---
<a id='intro'></a>

## Introduction

This notebook will teach your everything you need to know to use Python to create interactive dashboard's with Plotly's new Dash library! You will be able to create fully customization, interactive dashboards with the open source libraries of Plotly and Dash.

Contents:
- Learn about Plotly to create plots like Bar Charts, Line Charts, Scatter Plots, Heat Maps, and more!
- Create Layouts with Plotly's Dash library.
- Use Dash to create interactive components with Plotly.
- Learn how to connect multiple inputs and outputs with a dashboard.
- Update live interactive graphs with clicks, hover overs, and more.
- Connect the interactive dashboard to live updating data for streaming information.
- Learn how to secure your interactive dashboards with App Authorization.
- Deploy your interactive dashboards to the internet with services like Heroku.

---
<a id='set'></a>

## Environment Setup
- Install Python interpreter
- [Install Atom IDE](https://atom.io/)
- Install Atom's packages:
    - autocomplete-python package + kite ML package
    - platformio-ide-terminal / atom-terminal
- Configure Python virtual environment

---
<a id='libs'></a>

## Data Visualization libraries for Python

- **Matplotlib** for static image files.
- **Seaborn**, based on Matplotlib, designed to show static statistics plots, have cleaner syntax but only plots described in its documnetation are available.
- **Pandas**, main purpose is data analysis but uses simple .plot() calls (based on Matplotlib), limited scope of plot types, static plots.
- **Plotly** 
    - An open source general data visualization library focused on interactive visualizations. It has libraries for JavaScript, React, R and Python. 
    - The plots themselves cannot be connected to dynamic data sources (they are HTML files containing data visualization as of publishing). For that, they need **Dash**.
- **Dash** 
    - Allows you to create a full dashboard with multiple components, interactivity, and mutliple plots.
    - Produce a web application dashboard.

---
<a id='np'></a>

## Numpy Crash Course

**NumPy** is a scientific computing and mathematical library.

In [1]:
import numpy as np

In [2]:
mylist = [1,2,3,4]
np.array(mylist)

array([1, 2, 3, 4])

In [3]:
type(mylist)

list

In [4]:
arr = np.array(mylist)
type(arr)

numpy.ndarray

In [8]:
# Create np arrays
a = np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
a = np.arange(0,10,2)
a

array([0, 2, 4, 6, 8])

In [12]:
# 2-dimensional array
# rows,cols
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
type(1)

int

In [17]:
type(1.)

float

In [19]:
# Generate a random number within a range
np.random.randint(0,100)

50

In [20]:
# Create a random matrix (5,5) of integers 
# (uniform distribution, everynumber has the same likelihood of being picked)
np.random.randint(0,100,(5,5))

array([[31, 40, 24, 92, 89],
       [26, 96, 46, 18, 58],
       [88, 69, 93, 98, 35],
       [18, 88, 69, 89, 48],
       [62, 41, 66, 15, 60]])

In [24]:
# Create linearily spaced array bewteen 0,10 of 7 elements
np.linspace(0,10,7)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

In [25]:
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [27]:
np.linspace(0,10,12)

array([ 0.        ,  0.90909091,  1.81818182,  2.72727273,  3.63636364,
        4.54545455,  5.45454545,  6.36363636,  7.27272727,  8.18181818,
        9.09090909, 10.        ])

In [28]:
# Generate the same randoms numbers over and over again
np.random.seed(101)

In [29]:
np.random.randint(0,100,10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [30]:
arr = np.random.randint(0,100,100)
arr

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40, 49, 83,  8, 29, 59, 34, 44,
       72, 19, 10, 76, 95, 87,  0, 73,  8, 62, 36, 83, 99, 28, 63,  7, 10,
       52, 56, 38, 73, 52, 18, 71, 15, 44,  0, 12, 17, 75, 79, 97, 93, 24,
       36, 63, 19, 35, 30, 10, 60, 20, 27,  8, 86, 26, 87, 46, 47, 54, 86,
        9, 45,  2, 18, 58, 92, 11, 10, 94, 35, 28,  3, 83, 84, 47, 14, 69,
       60, 69, 51,  6, 88, 71, 68, 23, 35, 79, 98, 67, 82, 57, 77])

In [32]:
arr.max()

99

In [33]:
arr.min()

0

In [34]:
arr.mean()

47.96

In [35]:
# Get back an zero-based index location for the max value(s)
arr.argmax()

29

In [37]:
arr.argmin()

23

In [40]:
# Reshape your arr into another dimenstions
arr = np.random.randint(0,100,10)
arr

array([71, 20, 27, 75,  5, 49, 86, 89, 63, 82])

In [41]:
# rows, cols
arr.reshape(2,5)

array([[71, 20, 27, 75,  5],
       [49, 86, 89, 63, 82]])

In [42]:
# Build a matrix
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [43]:
# Get a specific value
# row, col
mat[5,2]

52

In [48]:
# Get entire column
# all rows, second column
col = mat[:,2]
col

array([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])

In [49]:
col.reshape(10,1)

array([[ 2],
       [12],
       [22],
       [32],
       [42],
       [52],
       [62],
       [72],
       [82],
       [92]])

In [51]:
# Get entire row
# row 2, all columns
row = mat[2,:]
row

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [52]:
# No need to reshape for rows
row.reshape(1,10)

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [53]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [54]:
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [55]:
# Get only values where values are > 50
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [85]:
l = 'A B C D'.split()
l

['A', 'B', 'C', 'D']

---
<a id='pd'></a>

## Pandas Crash Course

**Pandas** is a library built on top of **NumPy** which allows Python to read in data sets from various formats, such as CSV files. It provides a conveniest way of wrangling data in tabular form and calculate statistics.

In [56]:
import pandas as pd

In [57]:
df = pd.read_csv("data/udemy/dash/salaries.csv")
print(df)

     Name  Salary  Age
0    John   50000   34
1   Sally  120000   45
2  Alyssa   80000   27


In [58]:
# A series
df["Salary"]

0     50000
1    120000
2     80000
Name: Salary, dtype: int64

In [60]:
# A dataframe
df[["Salary"]]

Salary
0   50000
1  120000
2   80000

In [59]:
df[["Name", "Salary"]]

Name  Salary
0    John   50000
1   Sally  120000
2  Alyssa   80000

In [62]:
df["Salary"].min()

50000

In [63]:
df["Salary"].mean()

83333.33333333333

In [64]:
df

Name  Salary  Age
0    John   50000   34
1   Sally  120000   45
2  Alyssa   80000   27

In [66]:
# Conditional filtering
ser_of_bool = df["Age"] > 30
ser_of_bool

0     True
1     True
2    False
Name: Age, dtype: bool

In [67]:
df[ser_of_bool]

Name  Salary  Age
0   John   50000   34
1  Sally  120000   45

In [69]:
df[df["Age"] > 30]

Name  Salary  Age
0   John   50000   34
1  Sally  120000   45

In [73]:
# Show unique values in a Series
df[df["Age"] > 30]["Age"].unique()

array([34, 45])

In [74]:
# Show a number of unique values in a Series
df[df["Age"] > 30]["Age"].nunique()

2

In [75]:
df.columns

Index(['Name', 'Salary', 'Age'], dtype='object')

In [78]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [76]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
Name      3 non-null object
Salary    3 non-null int64
Age       3 non-null int64
dtypes: int64(2), object(1)
memory usage: 200.0+ bytes


In [77]:
df.describe()

Salary        Age
count       3.000000   3.000000
mean    83333.333333  35.333333
std     35118.845843   9.073772
min     50000.000000  27.000000
25%     65000.000000  30.500000
50%     80000.000000  34.000000
75%    100000.000000  39.500000
max    120000.000000  45.000000

In [80]:
# Create a dataframe from a numpy array
mat = np.arange(0,50).reshape(5,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [81]:
df = pd.DataFrame(data=mat)
df

0   1   2   3   4   5   6   7   8   9
0   0   1   2   3   4   5   6   7   8   9
1  10  11  12  13  14  15  16  17  18  19
2  20  21  22  23  24  25  26  27  28  29
3  30  31  32  33  34  35  36  37  38  39
4  40  41  42  43  44  45  46  47  48  49

In [82]:
mat = np.arange(0,10).reshape(5,2)
mat

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [84]:
df = pd.DataFrame(data=mat, columns=['A', 'B'], index=['a', 'b', 'c', 'd', 'e'])
df

A  B
a  0  1
b  2  3
c  4  5
d  6  7
e  8  9

---
<a id='res'></a>

## Resources

- [Course notes](https://github.com/Pierian-Data/Plotly-Dashboards-with-Dash)
- [Guide book](https://docs.google.com/document/d/1DjWL2DxLiRaBrlD3ELyQlCBRu7UQuuWfgjv9LncNp_M/edit?usp=sharing)
- [Public datasets](https://docs.google.com/document/d/1vI84_EpRTh4xfcFkTunFzZT0RWMcRSqdkPueVNBcLx8/edit)

In [ ]:
<img src="images/data_science.png" alt="" style="width: 400px;"/>

In [ ]:
---
<a id='intro'></a>